version: "3.9"

services:
  service-senior:
    image: $NEXUS_DOCKER_IP_PORT/repository/demo/service-a:senior
    container_name: servicesenior
    restart: always
    ports:
      - '8903:8999'
    networks:
      - contour-dev-net
    environment:
      - MSG=$MSG

networks:
  contour-dev-net:
    driver: bridge
