version: "3.9"
services:

  service-a:
    image: $CONTUR_TOOLS_IP:5000/repository/demo/service-a:dev
    container_name: serviceA
    restart: always
    ports:
      - '8901:8999'
    networks:
      - contour-dev-net

  service-b:
    image: $CONTUR_TOOLS_IP:5000/repository/demo/service-b:dev
    container_name: serviceB
    restart: always
    ports:
      - '8902:8999'
    networks:
      - contour-dev-net

networks:
  contour-dev-net:
    driver: bridge
